spring:
  cloud:
    gateway:
      routes:
        - id: third_party_route
          uri: lb://onemall-third-party
          predicates:
              - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>.*),/$\{segment}

        - id: ware_route
          uri: lb://onemall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: member_route
          uri: lb://onemall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: product_route
          uri: lb://onemall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}

        - id: onemall_host_route
          uri: lb://onemall-product
          predicates:
            - Host=onemall.com

        - id: onemall_search_route
          uri: lb://onemall-search
          predicates:
            - Host=search.onemall.com